name: first_workflow_for_revision
on: 
   repository_dispatch:
      types: 
        - test
jobs:
   first_job_here:
      runs-on: ubuntu-latest
      name: first_job 
      steps: 
        - name: first_step
          shell: bash 
          run: echo "goo goo"
           
