name: Receiver Workflow

on:
  repository_dispatch:
    types: [test]
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  display_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "goo goo"
          echo "Dispatch received successfully!"
