name: second-workflow
on: 
   schedule:
     - cron: "*/2 * * * *"
jobs: 
   first-job: 
        runs-on: ubuntu 
        steps:
          - name: first step 
            run:  echo "i am here" ; ls 
            # | 
            #         echo "iam here " 
            #          ls  
            shell: bash
            # name: second-workflow

# on:
#   schedule:
#     - cron: "*/2 * * * *"

# jobs:
#   first-job:                # Removed the hyphen here
#     runs-on: ubuntu-latest  # Moved this out of the list and fixed the name
#     steps:
#       - name: first step
#         run: |
#           echo "iam here"
#           ls
#         shell: bash