name: second workflow
on: 
   push: 
      branches:
        - "main"
jobs: 
  first-workflow-job:
    name: first
    runs-on: ubuntu-latest
    steps:
      - name:  run bash command 
        run: echo "hello this is my first step from my first job of my firft workflow"
        shell: bash  
      - name: second step
        uses:   actions/checkout@v6    
      
      - name: tryagain
        run : 'mvn clean package'
        shell: bash     
      - name: tryagain
        run : 'mvn test'
        shell: bash     