name: second workflow
on: 
  push:
    branches: ["main"]   
jobs:
     first-workflow-job:
         name:  first
         runs-on: ubuntu
         steps:
           - name: first step 
             run: echo "hello from my secondworkflow"
             shell: bash
           - name: second step  
             run: ls 
             uses: actions/checkout@v6
             shell: bash 


             